config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :users, :except => [:index, :show, :edit, :update, :destroy]

  resources :posts do
    resources :comments, :except => [:index, :show]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :content, :presence => true

end

app/models/message.rb
class Message
  def initialize(attributes)
    @to = attributes[:to]
    @from = attributes[:from]
    @body = attributes[:body]
  end

  def send_message
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => @body,
                      :To => @to,
                      :From => @from }

      ).execute
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  validates :title, :presence => true
  validates :body, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  validates :phone, presence: true
  validates :username, presence: true

  has_many :comments
  has_many :posts

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
    @comment.post_id = params[:post_id]
  end

  def create
    @post = Post.find(params[:post_id])
    @user = User.find(@post.user_id)
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      message = Message.new(body: "Someone has commented on your post", to: @user.phone, from: ENV['TWILIO_NUMBER'])
      message.send_message
      respond_to do |format|
        format.html do
          flash[:notice] = "Comment successfully added. Post author notified by SMS."
          redirect_to post_path(@post)
        end
        format.js { flash.now[:notice] = "Your comment was added. Post author notified by SMS." }
      end
    else
      respond_to do |format|
        format.html do
          flash[:alert] = "There were some errors..."
          render :new
        end
        format.js { flash.now[:alert] = "Comments can't be blank." }
      end
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      respond_to do |format|
        format.html do
          flash[:notice] = "Comment successfully updated"
          redirect_to post_path(@post)
        end
        format.js { flash.now[:notice] = "Comment updated." }
      end
    else
      respond_to do |format|
        format.html do
          flash[:alert] = "There were some errors..."
          render :edit
        end
        format.js { flash.now[:alert] = "An error occured. Please try again." }
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.destroy(params[:id])
    respond_to do |format|
      format.html do
        flash[:alert] = "Comment permanently deleted"
        redirect_to post_path(@post)
      end
      format.js { flash.now[:alert] = "Comment permanently deleted" }
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.all
    @comment = Comment.new
    @user = User.find(@post.user_id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
      if @post.save
        flash[:notice] = "Your post successfully created"
        redirect_to posts_path
      else
        render :new
      end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
      if @post.update(post_params)
        flash[:notice] = "You've successfully updated this post"
        redirect_to post_path
      else
        render :edit
      end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:alert] = "This post has been permanently destroyed"
    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:username], params[:password])

    if @user
      flash[:notice] = "You have logged in successfully"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem logging you in"
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've been successfully signed up."
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing you up. Please try again."
      redirect_to new_user_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :phone, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<li id="comment_<%= comment.id %>"><h7 class="comment-details">
  Posted by: |
  At: <%= comment.created_at %>
  <% if current_user.id == comment.user_id %>
   |
  <%= link_to "Edit", edit_post_comment_path(@post, comment, { method: :patch }), id: "edit_comment", remote: true %> |
  <%= link_to "Delete", post_comment_path(@post, comment),
:data => {:confirm => "Are you sure? There is no way to undo this.", method: :delete, remote: true } %></h7>
<% end %>
  <div class="comment-content">
    <%= comment.content %>
  </div>
</li>

app/views/comments/_edit.html.erb
<%= render 'form' %>

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment, remote: true %>

<%= form_for [@post, @comment], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :content %>
    <br>
    <%= f.text_area :content, cols: 50, rows: 7 %>
  </div>
  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/comments/_new.html.erb
<%= render 'form' %>

app/views/comments/create.js.erb
<% if @comment.save %>
  $('#new_comment').remove();
  $('#add_comment').show();
  $('#flashes').fadeIn(1000);
  $('#flashes').html('<%= j flash[:notice] %>');
  $('#flashes').fadeOut(1000);
  $('#comments').prepend('<%= j render(@comment) %>');
<% else %>
  $('#flashes').fadeIn(1000);
  $('#flashes').html('<%= j flash[:alert] %>');
  $('#flashes').fadeOut(slow);
<% end %>

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/edit.html.erb
<h4>Edit this comment:</h4>

<%= render 'form' %>

app/views/comments/edit.js.erb
$('#edit_comment').hide().after('<%= j render("edit") %>');

app/views/comments/new.js.erb
$('#add_comment').hide().after('<%= j render("new") %>');

app/views/comments/update.js.erb
$('#edit_comment_<%= @comment.id %>').remove();
$('#edit_comment').show();
$('#comment_<%= @comment.id %>').remove();
$('#comments').prepend('<%= j render(@comment) %>');
$('#flashes').fadeIn(1000);
$('#flashes').html('<%= j flash[:notice] %>');
$('#flashes').fadeOut(7000);

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Undead Journal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <h1>Undead Journal</h1>
    <% if !current_user %>
    <%= link_to "Sign Up", new_user_path %> |
    <%= link_to "Log In", log_in_path %>
    <% else %>
    Logged in as: <%= current_user.username %> |
    <%= link_to "Log Out", log_out_path %>
    <% end %>
  </div>
<hr>
  <div class="col-md-8 col-md-offset-2">

    <%= yield %>
    <div class="alert" id="flashes">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
  <br>
    <%= f.text_area :body, cols: 70, rows: 15 %>
  </div>
<%= f.submit :class => "btn btn-success" %>
<% end %>

app/views/posts/edit.html.erb
<h3>Editing <%= @post.title %></h3>

  <%= render 'form' %>

app/views/posts/index.html.erb
<h2>Posts Archive</h2>

<% if @posts.any? %>
  <ul>
    <% @posts.all.each do |post| %>
      <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
  </ul>
<% else %>
  <% if current_user %>
    There aren't any posts on this blog yet.
    Do you want to <%= link_to 'add one?', new_post_path %>
  <% end %>
<% end %>

<% if current_user && @posts.any? %>
  <hr>
  <%= link_to 'Add a new post', new_post_path %>
<% else %>
   <p>Please sign in or create an account to add new posts</p>
<% end %>

app/views/posts/new.html.erb
<h3>Write a new post</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="post-header">
  <h3><%= @post.title %></h3>
  <h4>Written on: <%= @post.created_at %> By: <%= @user.username %> </h4>
</div>

<div class="post-body">
  <p><%= @post.body %></p>
</div>

<hr>

<div class="post-comments">
  <h3>Comments</h3>
    <% if @post.comments.any? %>
      <ul id="comments">
        <%= render @comments.reverse %>
      </ul>
    <% else %>
      <p>No comments on this post.</p>
    <% end %>
</div>

<hr>
  <%= link_to "Add Comment", new_post_comment_path(@post), id: "add_comment", remote: true %>
<hr>
<div class="post-buttons">
  <%= link_to 'Return to posts list', posts_path, class: "btn btn-info" %>
  <% if current_user.id == @post.user_id %>
    | <%= link_to 'Edit this post', edit_post_path(@post), class: "btn btn-warning" %>
    | <%= link_to 'Delete this post', post_path(@post), class: "btn btn-danger",
    :data => {:confirm => 'Are you sure? There is no way to undo this', :method => 'delete' } %>
  <% end %>
</div>

app/views/users/new.html.erb
<h3>Create a new user account</h3>
<p>Tip: You can now enter a phone number to get an SMS alert when someone comments on your post.</p>

<%= form_for @user do |f| %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :phone %>
<%= f.text_field :phone %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit "Create Account" %>

<% end %>